site_name: personal-website
site_description: Tom Vo's personal website
repo_url: https://github.com/tvo25/personal-website
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/tvo25">tvo25</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
